export type FuelRow = {
  id: string
  assetNo: string
  type: 'Hours' | 'Km' | string
  requestNo: string
  date: string
  time: string
  requestedBy: string
  empNo: string
  storage: string
  stockcode: string
  uom: string
  qty: number
  reading: number
  costCenter: string
  fuelCard: string
  assetModel: string
  siteBranch: string
  department: string
  section: string
  element?: string
}

// Fallback dummy data
export const fuelRows: FuelRow[] = [
  {
    id: 'ddm-1',
    assetNo: 'DD001',
    type: 'Hours',
    requestNo: 'FL0101',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Wong Tiara',
    empNo: '12345',
    storage: 'Fuel Bay AA',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 100,
    reading: 20000,
    costCenter: 'Operation',
    fuelCard: 'FCDD001',
    assetModel: 'Diesel Drill Model DD-Z01',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 1',
    element: 'Fuel',
  },
  {
    id: 'ddm-2',
    assetNo: 'DD002',
    type: 'Hours',
    requestNo: 'FL0102',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Jun Hale',
    empNo: '12346',
    storage: 'Fuel Bay AA',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 150,
    reading: 18000,
    costCenter: 'Operation',
    fuelCard: 'FCDD002',
    assetModel: 'Diesel Drill Model DD-Z01',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 1',
    element: 'Fuel',
  },
  {
    id: 'e-a-1',
    assetNo: 'EXA001',
    type: 'Hours',
    requestNo: 'FL0102',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Wong Tiara',
    empNo: '12345',
    storage: 'Fuel Bay AA',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 200,
    reading: 22000,
    costCenter: 'Operation',
    fuelCard: 'FCEXA001',
    assetModel: 'Excavator EXC-AAA',
    siteBranch: 'Jakarta',
    department: 'Operations',
    section: 'Section 2',
    element: 'Fuel',
  },
  {
    id: 'e-a-2',
    assetNo: 'EXA002',
    type: 'Hours',
    requestNo: 'FL0103',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Wong Tiara',
    empNo: '12345',
    storage: 'Fuel Bay AA',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 75,
    reading: 19000,
    costCenter: 'Operation',
    fuelCard: 'FCEXA002',
    assetModel: 'Excavator EXC-AAA',
    siteBranch: 'Jakarta',
    department: 'Operations',
    section: 'Section 2',
    element: 'Fuel',
  },
  {
    id: 'e-b-1',
    assetNo: 'EXB001',
    type: 'Hours',
    requestNo: 'FL0104',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Jun Hale',
    empNo: '12346',
    storage: 'Fuel Bay AA',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 150,
    reading: 15000,
    costCenter: 'Operation',
    fuelCard: 'FCEXB001',
    assetModel: 'Excavator EXC-BBB',
    siteBranch: 'Jakarta',
    department: 'Operations',
    section: 'Section 3',
    element: 'Fuel',
  },
  {
    id: 'ht-a-1',
    assetNo: 'HL001',
    type: 'Km',
    requestNo: 'FL0105',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Wong Tiara',
    empNo: '12345',
    storage: 'Fuel Bay BB',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 175,
    reading: 20000,
    costCenter: 'Operation',
    fuelCard: 'FCHL001',
    assetModel: 'Haul Truck HT-007',
    siteBranch: 'Surabaya',
    department: 'Hauling',
    section: 'Section 4',
    element: 'Fuel',
  },
  {
    id: 'ht-a-2',
    assetNo: 'HL002',
    type: 'Km',
    requestNo: 'FL0106',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Jun Hale',
    empNo: '12346',
    storage: 'Fuel Bay BB',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 300,
    reading: 18000,
    costCenter: 'Operation',
    fuelCard: 'FCHL002',
    assetModel: 'Haul Truck HT-007',
    siteBranch: 'Surabaya',
    department: 'Hauling',
    section: 'Section 4',
    element: 'Fuel',
  },
  {
    id: 'ht-b-1',
    assetNo: 'HL003',
    type: 'Km',
    requestNo: 'FL0107',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Jun Hale',
    empNo: '12346',
    storage: 'Fuel Bay BB',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 125,
    reading: 22000,
    costCenter: 'Operation',
    fuelCard: 'FCHL003',
    assetModel: 'Haul Truck HTZ08',
    siteBranch: 'Surabaya',
    department: 'Hauling',
    section: 'Section 5',
    element: 'Fuel',
  },
  {
    id: 'ht-b-2',
    assetNo: 'HL004',
    type: 'Km',
    requestNo: 'FL0108',
    date: '2025-09-20',
    time: '00:00:00',
    requestedBy: 'Wong Tiara',
    empNo: '12345',
    storage: 'Fuel Bay BB',
    stockcode: 'SC0001 - Diesel Fuel',
    uom: 'Litre',
    qty: 125,
    reading: 19000,
    costCenter: 'Operation',
    fuelCard: 'FCHL004',
    assetModel: 'Haul Truck HTZ08',
    siteBranch: 'Surabaya',
    department: 'Hauling',
    section: 'Section 5',
    element: 'Fuel',
  },
]

export type fuelHistoryRow = {
  id: string
  assetNo: string
  assetModel: string
  date: string
  time: string
  type: 'Hours' | 'Km' | string
  requestNo: string
  requestedBy: string
  empNo: string
  stockcode: string
  uom: string
  qty: number
  unitCost: number
  amount: number
  reading: number
  costCenter: string
  fuelCard: string
}

export const fuelHistoryMap: Record<string, fuelHistoryRow[]> = {
  'DD001': [
    {
      id: 'fl-dd001-2025-09-20',
      assetNo: 'DD001',
      assetModel: 'Diesel Drill Model DD-Z01',
      date: '2025-09-20',
      time: '00:00:00',
      type: 'Hours',
      requestNo: 'FL0080',
      requestedBy: 'Wong Tiara',
      empNo: '12345',
      stockcode: 'SC0001 - Diesel Fuel',
      uom: 'Litre',
      qty: 200,
      unitCost: 1200000,
      amount: 240000000,
      reading: 19700,
      costCenter: 'Operation',
      fuelCard: 'FCDD001',
    },
    {
      id: 'fl-dd001-2025-09-15',
      assetNo: 'DD001',
      assetModel: 'Diesel Drill Model DD-Z01',
      date: '2025-09-15',
      time: '00:00:00',
      type: 'Hours',
      requestNo: 'FL0060',
      requestedBy: 'Jun Hale',
      empNo: '12346',
      stockcode: 'SC0001 - Diesel Fuel',
      uom: 'Litre',
      qty: 175,
      unitCost: 1200000,
      amount: 210000000,
      reading: 19500,
      costCenter: 'Operation',
      fuelCard: 'FCDD001',
    },
    {
      id: 'fl-dd001-2025-09-10',
      assetNo: 'DD001',
      assetModel: 'Diesel Drill Model DD-Z01',
      date: '2025-09-10',
      time: '00:00:00',
      type: 'Hours',
      requestNo: 'FL0040',
      requestedBy: 'Wong Tiara',
      empNo: '12345',
      stockcode: 'SC0001 - Diesel Fuel',
      uom: 'Litre',
      qty: 250,
      unitCost: 1200000,
      amount: 300000000,
      reading: 19200,
      costCenter: 'Operation',
      fuelCard: 'FCDD001',
    },
    {
      id: 'fl-dd001-2025-09-05',
      assetNo: 'DD001',
      assetModel: 'Diesel Drill Model DD-Z01',
      date: '2025-09-05',
      time: '00:00:00',
      type: 'Hours',
      requestNo: 'FL0020',
      requestedBy: 'Wong Tiara',
      empNo: '12345',
      stockcode: 'SC0001 - Diesel Fuel',
      uom: 'Litre',
      qty: 100,
      unitCost: 1200000,
      amount: 110000000,
      reading: 19000,
      costCenter: 'Operation',
      fuelCard: 'FCDD001',
    },
  ],
  'DD002': [
    {
      id: 'fl-dd001-2025-09-18',
      assetNo: 'DD001',
      assetModel: 'Diesel Drill Model DD-Z01',
      date: '2025-09-18',
      time: '00:00:00',
      type: 'Hours',
      requestNo: 'FL0085',
      requestedBy: 'Jun Hale',
      empNo: '12346',
      stockcode: 'SC0001 - Diesel Fuel',
      uom: 'Litre',
      qty: 150,
      unitCost: 1200000,
      amount: 180000000,
      reading: 17800,
      costCenter: 'Operation',
      fuelCard: 'FCDD002',
    },
  ],
}