export type ChecklistRow = {
  id: string
  assetNo: string
  operator: string
  originator: string
  checklistDate: string
  meterReading: number
  readingType: 'Hours' | 'Km' | string
  remarks: string
  assetModel: string
  siteBranch: string
  department: string
  section: string
  element?: string
}

// Fallback dummy data
export const checklistRows: ChecklistRow[] = [
  {
    id: 'ddm-1',
    assetNo: 'DD001',
    operator: 'Wong Tiara',
    originator: '12345',
    checklistDate: '2022-08-29',
    meterReading: 52970,
    readingType: 'Hours',
    remarks: 'Please follow up Leaking Engine and hose leaking',
    assetModel: 'Diesel Drill Model DD-Z01',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 1',
    element: 'Checklist',
  },
  {
    id: 'ddm-2',
    assetNo: 'DD002',
    operator: 'Jun Hale',
    originator: '12346',
    checklistDate: '2007-10-06',
    meterReading: 42364,
    readingType: 'Hours',
    remarks: 'Need follow up',
    assetModel: 'Diesel Drill Model DD-Z01',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 1',
    element: 'Checklist',
  },
  {
    id: 'e-a-1',
    assetNo: 'EXA001',
    operator: 'Wong Tiara',
    originator: '12345',
    checklistDate: '2009-04-08',
    meterReading: 50770,
    readingType: 'Hours',
    remarks: 'Need Repair',
    assetModel: 'Excavator EXC-AAA',
    siteBranch: 'Jakarta',
    department: 'Operations',
    section: 'Section 2',
    element: 'Checklist',
  },
  {
    id: 'e-a-2',
    assetNo: 'EXA002',
    operator: 'Wong Tiara',
    originator: '12345',
    checklistDate: '2008-07-29',
    meterReading: 47109,
    readingType: 'Hours',
    remarks: 'All Good',
    assetModel: 'Excavator EXC-AAA',
    siteBranch: 'Jakarta',
    department: 'Operations',
    section: 'Section 2',
    element: 'Checklist',
  },
  {
    id: 'e-b-1',
    assetNo: 'EXB001',
    operator: 'Jun Hale',
    originator: '12345',
    checklistDate: '2009-08-29',
    meterReading: 52970,
    readingType: 'Km',
    remarks: 'All Good',
    assetModel: 'Excavator EXC-BBB',
    siteBranch: 'Jakarta',
    department: 'Operations',
    section: 'Section 3',
    element: 'Checklist',
  },
  {
    id: 'ht-a-1',
    assetNo: 'HL001',
    operator: 'Wong Tiara',
    originator: '12345',
    checklistDate: '2007-11-29',
    meterReading: 42919,
    readingType: 'Km',
    remarks: 'All Good',
    assetModel: 'Haul Truck HTZ07',
    siteBranch: 'Surabaya',
    department: 'Hauling',
    section: 'Section 4',
    element: 'Checklist',
  },
  {
    id: 'ht-a-2',
    assetNo: 'HL002',
    operator: 'Jun Hale',
    originator: '12345',
    checklistDate: '2007-11-29',
    meterReading: 42919,
    readingType: 'Km',
    remarks: 'All Good',
    assetModel: 'Haul Truck HTZ07',
    siteBranch: 'Surabaya',
    department: 'Hauling',
    section: 'Section 4',
    element: 'Checklist',
  },
  {
    id: 'ht-b-1',
    assetNo: 'HL003',
    operator: 'Jun Hale',
    originator: '12345',
    checklistDate: '2006-08-05',
    meterReading: 37645,
    readingType: 'Km',
    remarks: 'All Good',
    assetModel: 'Haul Truck HTZAll Good8',
    siteBranch: 'Surabaya',
    department: 'Hauling',
    section: 'Section 5',
    element: 'Checklist',
  },
  {
    id: 'ht-b-2',
    assetNo: 'HL004',
    operator: 'Wong Tiara',
    originator: '12345',
    checklistDate: '2006-11-11',
    meterReading: 37645,
    readingType: 'Km',
    remarks: 'All Good',
    assetModel: 'Haul Truck HTZ08',
    siteBranch: 'Surabaya',
    department: 'Hauling',
    section: 'Section 5',
    element: 'Checklist',
  },
]