export type WorkorderRow = {
  id: string
  woNo: string
  woDescription: string
  assetNo: string
  priority: 'P#1' | 'P#2' | 'P#3' | string
  dueStart: string
  dueFinish: string
  dateStarted: string
  dateFinished: string
  status: 'New Request' | 'Waiting for Approval' | 'Approved' | 'Rejected' | 'Scheduled' | string
  breakdownType: string
  siteBranch: string
  department: string
  section: string
  element?: string
}

// Fallback dummy data
export const workorderRows: WorkorderRow[] = [
  {
    id: 'bm-1',
    woNo: 'WO2306-001',
    woDescription: 'Radiator Leaking',
    assetNo: 'DD001',
    priority: 'P#1',
    dueStart: '2023-06-04',
    dueFinish: '2025-06-05',
    dateStarted: '2023-06-04',
    dateFinished: '2023-06-05',
    status: 'Scheduled',
    breakdownType: 'Breakdown Maintenance',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 1',
    element: 'Work Order',
  },
  {
    id: 'bm-2',
    woNo: 'WO2306-002',
    woDescription: 'Need to change Alternator',
    assetNo: 'DD002',
    priority: 'P#1',
    dueStart: '2025-06-09',
    dueFinish: '2025-06-12',
    dateStarted: '2025-06-09',
    dateFinished: '2025-06-12',
    status: 'Scheduled',
    breakdownType: 'Breakdown Maintenance',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 1',
    element: 'Work Order',
  },
  {
    id: 'bm-3',
    woNo: 'WO2306-003',
    woDescription: 'Radiator Leaking',
    assetNo: 'EXA001',
    priority: 'P#2',
    dueStart: '2023-06-04',
    dueFinish: '2025-06-05',
    dateStarted: '2023-06-04',
    dateFinished: '2023-06-05',
    status: 'Scheduled',
    breakdownType: 'Breakdown Maintenance',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 1',
    element: 'Work Order',
  },
  {
    id: 'bm-4',
    woNo: 'WO2306-004',
    woDescription: 'Need to change Alternator',
    assetNo: 'DD001',
    priority: 'P#1',
    dueStart: '2025-06-09',
    dueFinish: '2025-06-12',
    dateStarted: '2025-06-09',
    dateFinished: '2025-06-12',
    status: 'Scheduled',
    breakdownType: 'Breakdown Maintenance',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 1',
    element: 'Work Order',
  },
  {
    id: 'cm-1',
    woNo: 'WO2306-003',
    woDescription: 'Radiator Leaking',
    assetNo: 'EXB001',
    priority: 'P#1',
    dueStart: '2025-06-04',
    dueFinish: '2025-06-05',
    dateStarted: '2025-06-04',
    dateFinished: '2025-06-05',
    status: 'Scheduled',
    breakdownType: 'Corrective Maintenance',
    siteBranch: 'Jakarta',
    department: 'Operations',
    section: 'Section 2',
    element: 'Work Order',
  },
  {
    id: 'pm-1',
    woNo: 'WO2306-005',
    woDescription: 'Radiator Leaking',
    assetNo: 'HL001',
    priority: 'P#1',
    dueStart: '2023-06-04',
    dueFinish: '2025-06-05',
    dateStarted: '2023-06-04',
    dateFinished: '2023-06-05',
    status: 'Scheduled',
    breakdownType: 'Preventive Maintenance',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 3',
    element: 'Work Order',
  },
  {
    id: 'pm-2',
    woNo: 'WO2306-006',
    woDescription: 'Need to change Alternator',
    assetNo: 'HL002',
    priority: 'P#2',
    dueStart: '2025-06-09',
    dueFinish: '2025-06-12',
    dateStarted: '2025-06-09',
    dateFinished: '2025-06-12',
    status: 'Scheduled',
    breakdownType: 'Preventive Maintenance',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 3',
    element: 'Work Order',
  },
  {
    id: 'wr-1',
    woNo: 'WO2306-007',
    woDescription: 'Radiator Leaking',
    assetNo: 'HL003',
    priority: 'P#1',
    dueStart: '2023-06-04',
    dueFinish: '2025-06-05',
    dateStarted: '2023-06-04',
    dateFinished: '2023-06-05',
    status: 'Scheduled',
    breakdownType: 'Work Request',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 4',
    element: 'Work Order',
  },
  {
    id: 'wr-2',
    woNo: 'WO2306-008',
    woDescription: 'Need to change Alternator',
    assetNo: 'HL004',
    priority: 'P#1',
    dueStart: '2025-06-09',
    dueFinish: '2025-06-12',
    dateStarted: '2025-06-09',
    dateFinished: '2025-06-12',
    status: 'Scheduled',
    breakdownType: 'Work Request',
    siteBranch: 'Jakarta',
    department: 'Mining',
    section: 'Section 4',
    element: 'Work Order',
  },
]